- app/src/main/res/values/styles.xml
Import styles and any other common attrs
[TCM-59](https://hyfnla.atlassian.net/browse/TCM-59)
N/A
> TCM-59 | Import styles from TRX Trainer

- app/src/main/java/com/trx/consumer/models/common/ClassModel.kt
- app/src/main/java/com/trx/consumer/models/common/ContentModel.kt
- app/src/main/java/com/trx/consumer/models/common/WaiverModel.kt
- app/src/main/java/com/trx/consumer/models/params/ContentParamsModel.kt
- app/src/main/java/com/trx/consumer/screens/content/ContentFragment.kt
- app/src/main/java/com/trx/consumer/screens/content/ContentViewModel.kt
- app/src/main/java/com/trx/consumer/screens/content/ContentViewState.kt
- app/src/main/java/com/trx/consumer/screens/testutility/TestUtilityFragment.kt
- app/src/main/java/com/trx/consumer/screens/testutility/TestUtilityViewModel.kt
- app/src/main/res/layout/fragment_content.xml
- app/src/main/res/layout/fragment_test_utility.xml
- app/src/main/res/navigation/nav_main.xml
- app/src/main/res/values/strings.xml
[TCM-105](https://hyfnla.atlassian.net/browse/TCM-105)
| State Book| State Plain|
|--------|--------|
|![content_state_book](https://user-images.githubusercontent.com/30659854/116007244-7b6afd80-a617-11eb-918e-06fba91c9fff.png)|![content_state_plain](https://user-images.githubusercontent.com/30659854/116007245-7c9c2a80-a617-11eb-9db7-6da566ce52b6.png)|
> TCM-105 | Build dummy content screen 

- app/build.gradle
- app/src/main/java/com/trx/consumer/base/BaseApi.kt
- app/src/main/java/com/trx/consumer/common/CommonHudView.kt
- app/src/main/java/com/trx/consumer/core/MainActivity.kt
- app/src/main/java/com/trx/consumer/managers/BackendManager.kt
- app/src/main/java/com/trx/consumer/models/UserModel.kt
- app/src/main/java/com/trx/consumer/models/core/RequestModel.kt
- app/src/main/java/com/trx/consumer/models/responses/UserResponseModel.kt
- app/src/main/java/com/trx/consumer/screens/home/HomeFragment.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginViewModel.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterFragment.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
- app/src/main/java/com/trx/consumer/views/input/InputView.kt
- app/src/main/java/com/trx/consumer/views/input/InputViewHandler.kt
- app/src/main/java/com/trx/consumer/views/input/InputViewListener.kt
- app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/layout/fragment_register.xml
- app/src/main/res/layout/layout_hud.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/trx/consumer/LoginViewModelTests.kt
- app/src/test/java/com/trx/consumer/RegisterViewModelTests.kt
Setup up authentication flows for user login and registration
[XPP-284](https://hyfnla.atlassian.net/browse/TCM-284)
[Login success](https://drive.google.com/file/d/1-39XefdngyGkDxNmUVz6FHSKvL0W3W4h/view?usp=sharing)
[Register confirm password validation](https://drive.google.com/file/d/1eljPM3LT9dMBi8ccaWpJyXJi2N2WVWv5/view?usp=sharing)
[Register email validation](https://drive.google.com/file/d/1wF14gnnmDGdcM8g1skeP0CQtnVEpeHxI/view?usp=sharing)
[Register password validation](https://drive.google.com/file/d/1rNiHT72o3a_5-y6Sn5FARAtRC8WHvFos/view?usp=sharing)
[Register success](https://drive.google.com/file/d/1LkWOc42ZzITWsXtXUR_IO_e1sIOpPCeT/view?usp=sharing)
> TCM-284 | Allow user to register and login

- app/build.gradle
- app/src/main/java/com/trx/consumer/screens/erroralert/ErrorAlertFragment.kt
- app/src/main/java/com/trx/consumer/screens/erroralert/ErrorAlertModel.kt
- app/src/main/java/com/trx/consumer/screens/erroralert/ErrorAlertViewModel.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginViewModel.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterFragment.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
- app/src/main/res/drawable/ic_img_error.xml
- app/src/main/res/layout/fragment_error_alert.xml
- app/src/main/res/navigation/nav_main.xml
- app/src/main/res/values/colors.xml
Bring over and display `ErrorAlert` in authentication flow
[TCM-294](https://hyfnla.atlassian.net/browse/TCM-294)
https://user-images.githubusercontent.com/39810816/118336079-9aea9d00-b4d6-11eb-938d-fa5b4b5a8317.mov
https://user-images.githubusercontent.com/39810816/118336087-9f16ba80-b4d6-11eb-8aca-a237002452bd.mov
> TCM-294 | Import and display `ErrorAlert`

- app/build.gradle
[TCM-307](https://hyfnla.atlassian.net/browse/TCM-307)
https://user-images.githubusercontent.com/24737954/118410966-123f3e80-b647-11eb-96a9-326f6d7bac4d.mov
> TCM-307 | Configure backend endpoints

- app/src/main/java/com/trx/consumer/managers/BackendManager.kt
- app/src/main/java/com/trx/consumer/models/common/FilterModel.kt
- app/src/main/java/com/trx/consumer/models/common/FilterOptionsModel.kt
- app/src/main/java/com/trx/consumer/models/common/TrainerModel.kt
- app/src/main/java/com/trx/consumer/models/common/VideoModel.kt
- app/src/main/java/com/trx/consumer/models/responses/VideoResponseModel.kt
- app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
- app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
- app/src/main/java/com/trx/consumer/screens/videoworkout/VideoWorkoutViewHolder.kt
- app/src/main/res/layout/fragment_discover.xml
- app/src/main/res/layout/fragment_filter_options.xml
- app/src/main/res/layout/fragment_filters.xml
[TCM-331](https://hyfnla.atlassian.net/browse/TCM-331)
https://user-images.githubusercontent.com/24737954/119208244-270c3f80-ba56-11eb-8957-22502265a6fa.mov
> TCM-331 | Connect filters flow

- app/src/main/java/com/trx/consumer/models/common/UserModel.kt
- app/src/main/java/com/trx/consumer/models/common/UserPlanModel.kt
- app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
- app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
- app/src/main/res/layout/fragment_plans.xml
- app/src/main/res/values/strings.xml
- Double check. Last pass. 
[TCM-392](https://hyfnla.atlassian.net/browse/TCM-392)
N/A
> TCM-392 | Rename Keyword Followup

- app/build.gradle
- app/src/devDebug/res/values/string.xml
- app/src/main/java/com/trx/consumer/core/MainApplication.kt
- app/src/main/java/com/trx/consumer/core/MainModule.kt
- app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
- app/src/main/java/com/trx/consumer/managers/ConfigManager.kt
- app/src/main/java/com/trx/consumer/models/common/AmplitudePropertyModel.kt
- app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
- app/src/main/java/com/trx/consumer/screens/home/HomeViewModel.kt
- build.gradle
[TCM-262](https://hyfnla.atlassian.net/browse/TCM-262)
> TCM-262  | Implement AnalyticsManager

- app/src/main/java/com/trx/consumer/common/CommonButton.kt
- app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginViewModel.kt
- app/src/main/res/layout/fragment_login.xml
- Enable/disable button based on contents in InputView
- Create function that enables button state and switches color based on two static values. 
[TCM-381](https://hyfnla.atlassian.net/browse/TCM-381)
| Initial | Filled |
|----|----|
|![initial](https://user-images.githubusercontent.com/27742105/119737212-c6a14780-be33-11eb-9b58-58635c43df4f.png)|![filled](https://user-images.githubusercontent.com/27742105/119737217-c86b0b00-be33-11eb-8b97-07a45d5cec20.png)|
https://user-images.githubusercontent.com/27742105/119737184-b7ba9500-be33-11eb-9dac-f5a2c0b5b590.mov
> TCM-381 | Button State Login

- app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
Use `setPrimaryEnabled` in `UpdateFragment`
[TCM-385](https://hyfnla.atlassian.net/browse/TCM-385)
N/A
> TCM-385 | Button State UpdateFragment 

- app/src/main/java/com/trx/consumer/managers/NavigationManager.kt
- app/src/main/java/com/trx/consumer/screens/live/LiveFragment.kt
- app/src/main/java/com/trx/consumer/screens/live/LiveViewModel.kt
- app/src/main/res/layout/fragment_live.xml
- app/src/main/res/menu/menu_bottom_nav.xml
- Update  the Live Screen to display the banner in Version 0. 
- Add `Live` to bottom navigation for Version 0 
[TCM-405](https://hyfnla.atlassian.net/browse/TCM-382)
| Old | New |
|----|----|
|![live_old](https://user-images.githubusercontent.com/27742105/119905889-ed2db400-bf01-11eb-8031-9f91e5a4a760.png)|![live_new](https://user-images.githubusercontent.com/27742105/119905886-eb63f080-bf01-11eb-89fa-b9e85948cc97.png)|
> TCM-405 - Live Screen Version 0

- app/src/main/java/com/trx/consumer/models/common/SettingsModel.kt
- app/src/main/java/com/trx/consumer/screens/home/HomeFragment.kt
- app/src/main/java/com/trx/consumer/screens/settings/SettingsFragment.kt
- app/src/main/java/com/trx/consumer/screens/settings/SettingsViewModel.kt
- app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionAdapter.kt
- app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionListener.kt
- app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_settings.xml
Matched figma desgin on ticket. 
[TCM-414](https://hyfnla.atlassian.net/browse/TCM-414)
> TCM-414 | Setup Settings screen for v0

- app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
- Add `signUpUserType` to the params in Register. This will allow users to register on android. 
[TCM-491](https://hyfnla.atlassian.net/browse/TCM-419)
No video but register will bring you to update when signing up with an unclaimed email, valid password, and agreeing to terms. The user will receive a verification message with the email they registered with.
> TCM-419 | Add signUpUserType to Register params

- app/build.gradle
- app/src/main/java/com/trx/consumer/managers/BackendManager.kt
- app/src/main/java/com/trx/consumer/managers/CacheManager.kt
- app/src/main/java/com/trx/consumer/models/responses/UserResponseModel.kt
- app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
- app/src/main/java/com/trx/consumer/screens/email/EmailViewModel.kt
- app/src/main/java/com/trx/consumer/screens/email/EmailViewState.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
- app/src/main/java/com/trx/consumer/screens/login/LoginViewModel.kt
- app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewModel.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterFragment.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
- app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
- app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
- app/src/main/res/layout/fragment_update.xml
- app/src/main/res/values/strings.xml
- Handled all the major issues on the ticket. 
Note: Ashley's account will crash the app because of GSON errors. Something to consider moving forward. Onboarding ticket follow up since theres a scrollview being used in onboarding [ticket](https://hyfnla.atlassian.net/browse/TCM-422)
[TCM-410](https://hyfnla.atlassian.net/browse/TCM-410)
**First time login will show Onboarding. Logging out and registering a new account on the device will not show onboarding**
https://user-images.githubusercontent.com/27742105/120051485-aad5a700-bfd5-11eb-985f-9a0885b6a614.mov
**Registering for the first time will show the Onboarding. Logging out and logging in with a new account will not show the onboarding.**
https://user-images.githubusercontent.com/27742105/120051692-77dfe300-bfd6-11eb-93e9-54f4e2c207f3. …
> TCM-410 | Consolidate Authentication

- app/build.gradle
- app/src/main/java/com/trx/consumer/managers/UtilityManager.kt
Prepare for first build
[Release notes](https://hyfnla.atlassian.net/issues/?jql=project%20%3D%20%22TCM%22%20AND%20fixVersion%20%3D%20%22TXC%20Android%20v0.0.0.1%22)
[TCM-159](https://hyfnla.atlassian.net/browse/TCM-159)
> TCM-159 | Version 0.0.1 Build 1

- app/build.gradle
- app/google-services.json
- app/src/main/java/com/trx/consumer/managers/ConfigManager.kt
- app/src/main/java/com/trx/consumer/managers/LogManager.kt
- build.gradle
Add ability to record Firebase logs and exceptions for release versions
[TCM-437](https://hyfnla.atlassian.net/browse/TCM-437)
https://user-images.githubusercontent.com/39810816/120264145-cbfef780-c262-11eb-8b96-d2d9d0ccc6ed.mov
> TXM-437 | Set up Firebase Crashlytics

- app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewModel.kt
- app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
- app/src/main/res/values/strings.xml
Copy changes from ticket. 
[TCM-460](https://hyfnla.atlassian.net/browse/TCM-460)
https://user-images.githubusercontent.com/27742105/120760307-d28ea880-c4c8-11eb-9055-9ad86e74ae29.mov
> TCM-460 | Copy notes for v0

- app/src/main/java/com/trx/consumer/screens/alert/AlertViewModel.kt
Perform back action on close tap in Alert
[TCM-499](https://hyfnla.atlassian.net/browse/TCM-499)
https://user-images.githubusercontent.com/39810816/121073163-cd1ab200-c797-11eb-8d7e-3b8c4614e9bb.mov
> TCM-499 | Perform back action on close tap in `Alert`

- app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
- app/src/main/res/layout/fragment_workout.xml
- app/src/main/res/values/strings.xml
[TCM-492](https://hyfnla.atlassian.net/browse/TCM-492)
https://user-images.githubusercontent.com/24737954/121410052-062d6080-c917-11eb-8d20-91b4afd1e295.mov
> TCM-492 |  Add equipments section

- app/build.gradle
[Release Note](https://hyfnla.atlassian.net/sr/jira.issueviews:searchrequest-printable/temp/SearchRequest.html?jqlQuery=project+%3D+%22TCM%22+AND+fixVersion+%3D+%22TXC+Android+v0.1.0.2%22&atl_token=B1U4-ZV3W-MSGB-7BON_7fbd9c0e2a1441ce93d1f333db6f15e9447f56a5_lin&tempMax=1000)
[TCM-513](https://hyfnla.atlassian.net/browse/TCM-513)
> TCM-513 | Prepare `Version 0.1.0 Build 2`

- app/src/main/java/com/trx/consumer/screens/home/HomeFragment.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/layout_promo_section.xml
- app/src/main/res/layout/layout_video_workout_section.xml
Add space if `For You` section is empty. 
[TCM-477](https://hyfnla.atlassian.net/browse/TCM-477)
https://user-images.githubusercontent.com/27742105/121080434-457d7500-c790-11eb-8282-6a3ba94b2403.mov
https://user-images.githubusercontent.com/27742105/121080443-47dfcf00-c790-11eb-956c-117cc776b769.mov
> TCM-477 | For You section

- app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
- app/src/main/java/com/trx/consumer/screens/videos/VideosViewModel.kt
- app/src/main/res/layout/fragment_videos.xml
- Remove button to start workout, no related workouts label. 
[TCM-490](https://hyfnla.atlassian.net/browse/TCM-490)
https://user-images.githubusercontent.com/27742105/121099272-6653c380-c7ac-11eb-875c-85611c7a37eb.mov
| | | Most Recent Changes |
|----|----|----|
|![Screenshot_1623107467](https://user-images.githubusercontent.com/27742105/121099290-6ce23b00-c7ac-11eb-9a8b-fa318ccbd107.png)|![Screenshot_1623107478](https://user-images.githubusercontent.com/27742105/121099300-72d81c00-c7ac-11eb-84cd-e1dd93778d25.png)|![image](https://user-images.githubusercontent.com/27742105/121609737-5ab10880-ca09-11eb-866b-410e5982664c.png)|
> TCM-490 | Improve `Videos` screen

- app/src/main/java/com/trx/consumer/models/common/SettingsModel.kt
- app/src/main/java/com/trx/consumer/screens/settings/SettingsFragment.kt
- app/src/main/java/com/trx/consumer/screens/settings/SettingsViewModel.kt
- app/src/main/res/values/strings.xml
[TCM-427](https://hyfnla.atlassian.net/browse/TCM-427)
https://user-images.githubusercontent.com/24737954/122622059-58276200-d04c-11eb-9ac5-9347bf6cf681.mov
> TCM-427 | Polish settings screen for v1

- app/build.gradle
Prepare for new build
[Release notes](https://hyfnla.atlassian.net/issues/?jql=project%20%3D%20%22TCM%22%20AND%20fixVersion%20%3D%20%22TXC%20Android%20v0.1.1.3%22)
[TCM-575](https://hyfnla.atlassian.net/browse/TCM-575)
> TCM-575 | Version 0.1.1 Build 3

- app/build.gradle
- app/src/main/java/com/trx/consumer/core/MainModule.kt
- app/src/main/java/com/trx/consumer/managers/ConfigManager.kt
- build.gradle
[TCM-442](https://hyfnla.atlassian.net/browse/TCM-442)
> TCM-442 | Setup firebase remote config connection

- app/src/main/java/com/trx/consumer/managers/BackendManager.kt
- app/src/main/java/com/trx/consumer/models/common/EndpointModel.kt
[TCM-600](https://hyfnla.atlassian.net/browse/TCM-600)
https://user-images.githubusercontent.com/24737954/122995520-9380a400-d35e-11eb-8eb1-a1cefd316d0f.mov
> TCM-600 | Promos on Homepage

- app/src/main/java/com/trx/consumer/core/MainModule.kt
- app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
- app/src/main/java/com/trx/consumer/managers/NativePurchaseManager.kt
- app/src/main/java/com/trx/consumer/screens/memberships/MembershipsViewModel.kt
- app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
Implement an API to get purchases native to google play account
[TCM-624](https://hyfnla.atlassian.net/browse/TCM-624)
> TCM-624 | Implement `NativePurchaseManager`

- app/src/main/java/com/trx/consumer/base/BaseFragment.kt
- app/src/main/java/com/trx/consumer/screens/maintenance/MaintenanceFragment.kt
[lTCM-440](https://hyfnla.atlassian.net/browse/TCM-440)
https://user-images.githubusercontent.com/24737954/123157525-7fe94200-d41f-11eb-8ef2-f7130e4f201a.mov
https://user-images.githubusercontent.com/24737954/123157547-85df2300-d41f-11eb-8f49-c8455bdc6199.mov
> TCM-440 | Introduce maintenance screen

- app/src/main/java/com/trx/consumer/managers/BackendManager.kt
- app/src/main/java/com/trx/consumer/managers/IAPManager.kt
Reset revcat user on logout
[TCM-589](https://hyfnla.atlassian.net/browse/TCM-589)
N/A
> TCM-589 | Reset revcat user on logout

- app/src/main/java/com/trx/consumer/models/common/MembershipModel.kt
Display correct billing period
[TCM-583](https://hyfnla.atlassian.net/browse/TCM-583)
> TCM-583 | Display correct billing period

- app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
- app/src/main/java/com/trx/consumer/models/common/MembershipModel.kt
- app/src/main/java/com/trx/consumer/models/common/UserModel.kt
- app/src/main/java/com/trx/consumer/screens/memberships/MembershipsViewModel.kt
- app/src/main/java/com/trx/consumer/screens/memberships/list/MembershipsViewHolder.kt
- app/src/main/java/com/trx/consumer/screens/restore/RestoreFragment.kt
- app/src/main/res/layout/fragment_restore.xml
- app/src/main/res/layout/row_membership.xml
- app/src/main/res/values/strings.xml
Polish for release
[TCM-632](https://hyfnla.atlassian.net/browse/TCM-632)
[Restore](https://drive.google.com/file/d/1MGeIuEYeucw6eVlvL-tRc0OLH80alpPE/view?usp=sharing)
[Cancelled state](https://drive.google.com/file/d/1Leu2mYpu3fhNEUT4t7k_ozmHO2prpCaf/view?usp=sharing)
[Billing dates order](https://drive.google.com/file/d/1BCwwm4CP0RA-wimqRLosIS3iJjh_TOdk/view?usp=sharing)
[Ashley user settings](https://drive.google.com/file/d/19oOWz6fFTG9y58A9Hc_Tg9AOzLWMGtIc/view?usp=sharing)
[Billing period](https://drive.google.com/file/d/1wR63aUaQLFuo5r8gkGwKimjg7oagjTnn/view?usp=sharing)
> TCM-632 | Polish for release

- app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
Hide trainer profile button
[TCM-640](https://hyfnla.atlassian.net/browse/TCM-640)
> TCM-640 | Hide trainer profile button

- app/build.gradle
[Release Note](https://hyfnla.atlassian.net/sr/jira.issueviews:searchrequest-printable/temp/SearchRequest.html?jqlQuery=statusCategory+%3D+indeterminate+AND+project+%3D+27575+AND+fixVersion+%3D+25137+ORDER+BY+priority+DESC%2C+key+ASC&atl_token=B1U4-ZV3W-MSGB-7BON_54ad4d0ea4b00b773957c7bc0ca222bad34d1f22_lin&tempMax=1000)
[TCM-645](https://hyfnla.atlassian.net/browse/TCM-645)
> TCM-645 | Prepare `Version 10.0.0 Build 1000003`

- app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
- app/src/main/res/layout/fragment_videos.xml
Hide description if not available
[TCM-674](https://hyfnla.atlassian.net/browse/TCM-674)
> Hide description if not available

- app/build.gradle
- app/src/main/java/com/trx/consumer/common/CommonButton.kt
- app/src/main/java/com/trx/consumer/common/CommonLabel.kt
- app/src/main/java/com/trx/consumer/extensions/StringExtensions.kt
- app/src/main/java/com/trx/consumer/models/common/AlertModel.kt
- app/src/main/java/com/trx/consumer/screens/alert/AlertFragment.kt
- app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
- app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
- app/src/main/res/layout/fragment_memberships.xml
- app/src/main/res/values/strings.xml
[TCM-672](https://hyfnla.atlassian.net/browse/TCM-672)
https://user-images.githubusercontent.com/24737954/124195598-9c205b00-da7f-11eb-8a3c-2848c4739f5b.mov
| Info button membership screen | Info button alert dialog |
|---|--|
|![Screenshot_1625177744](https://user-images.githubusercontent.com/24737954/124195399-3e8c0e80-da7f-11eb-9985-2f5fab1312f8.png)|![Screenshot_1625167735](https://user-images.githubusercontent.com/24737954/124180461-1396c000-da69-11eb-9119-401f52e052e8.png)|
> TCM-672 | improve membership

- app/build.gradle
[Release notes](https://hyfnla.atlassian.net/issues/?jql=project%20%3D%20%22TCM%22%20AND%20fixVersion%20%3D%20%22TXC%20Android%20v10.0.0.1000004%22)
[TCM-665](https://hyfnla.atlassian.net/browse/TCM-665)
> TCM-665 | Version 10.0.0 Build 1000004

- app/src/main/res/drawable/ic_img_camera_inactive.xml
- app/src/main/res/drawable/ic_img_microphone_inactive.xml
[TCM-689](https://hyfnla.atlassian.net/browse/TCM-689)
> TCM-689 | Inactive images for Camera and Microphone

- app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
- app/src/main/java/com/trx/consumer/screens/groupplayer/GroupPlayerActivity.kt
- app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
- app/src/main/res/values/attrs.xml
[TCM-725](https://hyfnla.atlassian.net/browse/TCM-725)
https://user-images.githubusercontent.com/24737954/125126360-d6a57b80-e0af-11eb-930e-60f322064528.mov
> TCM-725 | Improve touches for CommonStateButton

- app/build.gradle
[Release Notes](https://hyfnla.atlassian.net/sr/jira.issueviews:searchrequest-printable/temp/SearchRequest.html?jqlQuery=project+%3D+%22TCM%22+AND+fixVersion+%3D+%22TXC+Android+v10.0.1.1000010%22&atl_token=B1U4-ZV3W-MSGB-7BON_86b5d35fa3cddc7cfc7e3f4e4985994afe1206cd_lin&tempMax=1000)
[TCM-680](https://hyfnla.atlassian.net/browse/TCM-680)
> TCM-680 | Version 10.0.1 Build 1000010

- app/src/main/res/values/strings.xml
[TCM-698](https://hyfnla.atlassian.net/browse/TCM-698)
| BEFORE) | AFTER |
|--------|------|
|![onboarding_before](https://user-images.githubusercontent.com/30659854/125174483-84a74780-e1ce-11eb-89f9-cb40c3fc61f2.png)|![onboarding_after](https://user-images.githubusercontent.com/30659854/125174482-82dd8400-e1ce-11eb-95a2-adca96e2de49.png)|
> TCM-698 | Change welcome screen copy

- app/src/main/java/com/trx/consumer/core/MainModule.kt
- app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
- app/src/main/java/com/trx/consumer/managers/BackendManager.kt
- Inject analytics manager to backendmanager, call `AnalyticsManager.setUserId(id: String)` in `BackendManager.user()`.
[TCM-734](https://hyfnla.atlassian.net/browse/TCM-734)
> TCM-734 | Add UserId for Amplitude 

- app/build.gradle
[Release Notes](https://hyfnla.atlassian.net/sr/jira.issueviews:searchrequest-printable/temp/SearchRequest.html?jqlQuery=project+%3D+%22TCM%22+AND+fixVersion+%3D+%22TXC+Android+v10.0.2.1000012%22&atl_token=B1U4-ZV3W-MSGB-7BON_d290fbe6b1c4b435d5248e50e8f6ea908d6bf5a4_lin&tempMax=1000)
[TCM-730](https://hyfnla.atlassian.net/browse/TCM-730)
> TCM-730 | Version 10.0.2 Build 1000012

- app/build.gradle
[TCM-757](https://hyfnla.atlassian.net/browse/TCM-757)
> TCM-757 | Prepare `Version 10.0.3 Build 1000013`

- app/src/main/res/layout-land/activity_group_player.xml
- app/src/main/res/layout-land/activity_private_player.xml
- app/src/main/res/layout/activity_group_player.xml
- app/src/main/res/layout/activity_private_player.xml
- Follow figma layout on ticket. 
[TCM-693](https://hyfnla.atlassian.net/browse/TCM-693)
| Landscape | Portrait |
|----|----|
|![Screenshot_1626732474](https://user-images.githubusercontent.com/27742105/126233777-9f8436f5-c16c-470f-96ac-8e891e4c7f54.png)|![Screenshot_1626732464](https://user-images.githubusercontent.com/27742105/126233780-12d2b2d3-043e-44a0-8ac3-1d37f612362a.png)|
> TCM-693 | Leaner Group/Private Player

- app/build.gradle
- app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
- app/src/main/java/com/trx/consumer/extensions/CommonImageViewExtensions.kt
- app/src/main/java/com/trx/consumer/screens/alert/AlertFragment.kt
- app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
- app/src/main/res/layout/row_video_workout.xml
[TCM-759](https://hyfnla.atlassian.net/browse/TCM-759)
| Home | Workouts |
|----|----|
|![image](https://user-images.githubusercontent.com/27742105/126715670-2c9d6ccb-0102-4081-88ce-da75b76bc210.png)|![image](https://user-images.githubusercontent.com/27742105/126715636-ef45ae70-80fb-4808-a098-e6414e7fd934.png)|
> TCM-759 | Video Workout Placeholder

- app/build.gradle
[Release Notes](https://hyfnla.atlassian.net/sr/jira.issueviews:searchrequest-printable/temp/SearchRequest.html?jqlQuery=project+%3D+%22TCM%22+AND+fixVersion+%3D+%22TXC+Android+v10.0.4.1000014%22&atl_token=B1U4-ZV3W-MSGB-7BON_d51c9ca914c728eec38f5fb3b339e876b66cd8ad_lin&tempMax=1000)
[TCM-769](https://hyfnla.atlassian.net/browse/TCM-769)
> TCM-769 | Prepare `Version 10.0.4 Build 1000014`
